// <auto-generated />
using System;
using Incidents.DataAccess.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Incidents.Migrations
{
    [DbContext(typeof(IncidentsDBContext))]
    [Migration("20220105114106_init2")]
    partial class init2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Incidents.DataAccess.Entities.Accounts", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AccountId"));

                    b.Property<Guid?>("IncidentName")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IncidentsIncidentName")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AccountId");

                    b.HasIndex("IncidentName");

                    b.HasIndex("IncidentsIncidentName");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Incidents.DataAccess.Entities.Contacts", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ContactId"));

                    b.Property<int?>("AccountsAccountId")
                        .HasColumnType("integer");

                    b.Property<int?>("AccountsId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ContactId");

                    b.HasIndex("AccountsAccountId");

                    b.HasIndex("AccountsId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("Incidents.DataAccess.Entities.Incidents", b =>
                {
                    b.Property<Guid>("IncidentName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Name")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IncidentName");

                    b.ToTable("Incidents");
                });

            modelBuilder.Entity("Incidents.DataAccess.Entities.Accounts", b =>
                {
                    b.HasOne("Incidents.DataAccess.Entities.Incidents", "Incidents")
                        .WithMany("Accounts")
                        .HasForeignKey("IncidentName");

                    b.HasOne("Incidents.DataAccess.Entities.Incidents", null)
                        .WithMany()
                        .HasForeignKey("IncidentsIncidentName");

                    b.Navigation("Incidents");
                });

            modelBuilder.Entity("Incidents.DataAccess.Entities.Contacts", b =>
                {
                    b.HasOne("Incidents.DataAccess.Entities.Accounts", null)
                        .WithMany()
                        .HasForeignKey("AccountsAccountId");

                    b.HasOne("Incidents.DataAccess.Entities.Accounts", "Accounts")
                        .WithMany("Contacts")
                        .HasForeignKey("AccountsId");

                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("Incidents.DataAccess.Entities.Accounts", b =>
                {
                    b.Navigation("Contacts");
                });

            modelBuilder.Entity("Incidents.DataAccess.Entities.Incidents", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
